[package]
name = "ariel-os-embassy-common"
version = "0.3.0"
edition.workspace = true
rust-version.workspace = true
repository.workspace = true
license.workspace = true

[dependencies]
ariel-os-buildinfo = { workspace = true }
ariel-os-utils = { workspace = true }
const-sha1 = { version = "0.3.0", default-features = false }
defmt = { workspace = true, optional = true }
embassy-executor = { workspace = true }
embassy-time = { workspace = true }
embedded-hal = { workspace = true }
embedded-hal-async = { workspace = true }
fugit = { workspace = true, optional = true }
static_cell = { workspace = true, optional = true }
trouble-host = { workspace = true, optional = true }

[features]
## Enables GPIO interrupt support.
external-interrupts = []

## Enables I2C support.
i2c = ["dep:fugit"]

## Enables SPI support.
spi = ["dep:fugit"]

## Enables UART support.
uart = []

defmt = ["dep:defmt", "fugit?/defmt"]

executor-thread = []

_test = ["external-interrupts", "i2c", "spi", "uart"]

ble = ["dep:static_cell", "dep:trouble-host"]

cellular-networking = []

[lints]
workspace = true
