[package]
name = "ariel-os-debug-log"
version = "0.2.0"
license.workspace = true
edition.workspace = true
rust-version.workspace = true
repository.workspace = true

[lints]
workspace = true

[package.metadata.feature-groups]
logging-facade.xor = { features = ["defmt", "log"] }

[dependencies]
defmt = { workspace = true, optional = true }
featurecomb = { workspace = true }
log = { workspace = true, optional = true }

[features]
## Enables `defmt` as logging facade.
defmt = ["dep:defmt"]
## Enables `log` as logging facade.
log = ["dep:log"]

_test = []
