[package]
name = "ariel-os-rp"
version = "0.2.0"
license.workspace = true
edition.workspace = true
rust-version.workspace = true
repository.workspace = true

[lints]
workspace = true

[dependencies]
cfg-if = { workspace = true }
defmt = { workspace = true, optional = true }
embassy-embedded-hal = { workspace = true, optional = true }
embassy-net-driver-channel = { workspace = true, optional = true }
embassy-rp = { workspace = true, default-features = false, features = [
  "optfield",
  "rt",
  "time-driver",
  "unstable-pac",
  # "unstable-traits",
] }
embedded-hal-async = { workspace = true }
paste = { workspace = true }
ariel-os-debug = { workspace = true }
ariel-os-embassy-common = { workspace = true }
ariel-os-random = { workspace = true, optional = true }
ariel-os-utils = { workspace = true }
static_cell = { workspace = true, optional = true }

# rpi-pico-w cyw43
cyw43 = { version = "0.3.0", features = ["firmware-logs"], optional = true }
cyw43-pio = { version = "0.4.0", optional = true }

# BLE dependencies
embassy-sync = { workspace = true, optional = true }
bt-hci = { workspace = true, optional = true }
trouble-host = { workspace = true, optional = true }

[target.'cfg(context = "cortex-m")'.dependencies]
embassy-executor = { workspace = true, default-features = false, features = [
  "arch-cortex-m",
] }

[target.'cfg(context = "rp2040")'.dependencies]
embassy-rp = { workspace = true, default-features = false, features = [
  "rp2040",
] }

[target.'cfg(context = "rp235xa")'.dependencies]
embassy-rp = { workspace = true, default-features = false, features = [
  "rp235xa",
  "binary-info",
] }

[features]
## Enables GPIO interrupt support.
external-interrupts = ["ariel-os-embassy-common/external-interrupts"]

## Enables seeding the random number generator from hardware.
hwrng = ["dep:ariel-os-random"]

## Enables I2C support.
i2c = ["ariel-os-embassy-common/i2c"]

## Enables SPI support.
spi = ["dep:embassy-embedded-hal", "ariel-os-embassy-common/spi"]

## Enables storage support.
storage = []

## Enables USB support.
usb = []

## Enables Bluetooth Low Energy support.
ble = ["ariel-os-embassy-common/ble"]

ble-cyw43 = [
  "dep:trouble-host",
  "dep:bt-hci",
  "dep:embassy-sync",
  "_cyw43",
  "cyw43?/bluetooth",
  "ariel-os-random/csprng",
  "ble",
]
ble-peripheral = ["ble-cyw43"]
ble-central = ["ble-cyw43"]

## Enables defmt support.
defmt = ["dep:defmt", "cyw43?/defmt", "embassy-rp/defmt"]

## Enables Wi-Fi support.
wifi = []

## Enables support for the CYW43 Wi-Fi chip.
wifi-cyw43 = ["_cyw43", "wifi"]

## Enables the interrupt executor.
executor-interrupt = ["embassy-executor/executor-interrupt"]

_test = ["embassy-rp/rp2040", "external-interrupts", "i2c", "spi"]

_cyw43 = [
  "dep:cyw43",
  "dep:cyw43-pio",
  "dep:embassy-net-driver-channel",
  "dep:static_cell",
]
