[package]
name = "ariel-os-threads"
version = "0.2.0"
edition.workspace = true
rust-version.workspace = true
description = "generic embedded scheduler & IPC"
repository.workspace = true
license.workspace = true
include = ["src/**/*", "README.md"]

[dependencies]
ariel-os-debug = { workspace = true }
ariel-os-runqueue = { workspace = true }
ariel-os-utils = { workspace = true }
cfg-if = { workspace = true }
critical-section = { workspace = true }
embassy-time = { workspace = true }
embassy-time-driver = { workspace = true }
linkme = { workspace = true }
paste = { workspace = true }
portable-atomic = { workspace = true }
static_cell = { workspace = true }

defmt = { workspace = true, optional = true }

[target.'cfg(context = "esp32")'.dependencies]
esp-hal = { workspace = true, features = ["esp32"] }

[target.'cfg(context = "xtensa")'.dependencies]
xtensa-lx-rt = { workspace = true, features = ["float-save-restore"] }

[target.'cfg(context = "esp32c3")'.dependencies]
esp-hal = { workspace = true, features = ["esp32c3"] }

[target.'cfg(context = "esp32c6")'.dependencies]
esp-hal = { workspace = true, features = ["esp32c6"] }

[target.'cfg(context = "esp32s2")'.dependencies]
esp-hal = { workspace = true, features = ["esp32s2"] }
static_cell = { workspace = true, optional = true }

[target.'cfg(context = "esp32s3")'.dependencies]
esp-hal = { workspace = true, features = ["esp32s3"] }
static_cell = { workspace = true, optional = true }

[target.'cfg(context = "cortex-m")'.dependencies]
# cortex-m specifics
cortex-m = { workspace = true }
cortex-m-rt = { workspace = true }
cortex-m-semihosting = { workspace = true }
panic-semihosting = { version = "0.6.0", features = ["exit"] }

[target.'cfg(context = "native")'.dependencies]
atomic-wait = { version = "1.1.0" }
critical-section = { workspace = true, features = ["restore-state-bool"] }

[target.'cfg(context = "rp")'.dependencies]
embassy-rp = { workspace = true, optional = true }
rp-pac = { workspace = true, optional = true }
static_cell = { workspace = true, optional = true }

[features]
defmt = ["dep:defmt", "ariel-os-runqueue/defmt"]
single-core = []
multi-core = [
  "dep:embassy-rp",
  "dep:rp-pac",
  "dep:static_cell",
  "embassy-rp/fifo-handler",
  "idle-threads",
]
infini-core = []
core-affinity = ["multi-core"]
idle-threads = []

_test = ["single-core"]

[lints]
workspace = true
