[package]
name = "ariel-os-sensors-registry"
version = "0.1.0"
edition.workspace = true
rust-version = "1.90"
repository.workspace = true
license.workspace = true

[dependencies]
ariel-os-sensors = { workspace = true }
linkme = { workspace = true }

[features]
_test = []

[lints]
workspace = true
