[book]
authors = [
  "Kaspar Schleiser",
  "Emmanuel Baccelli",
  "Christian Ams√ºss",
  "Elena Frank",
  "Nils Ponsard",
]
language = "en"
src = "src"
title = "Ariel OS manual"

[output.html]
git-repository-url = "https://github.com/ariel-os/ariel-os"
edit-url-template = "https://github.com/ariel-os/ariel-os/edit/main/book/{path}"
[output.html.print]
enable = false # Links to internal pages in print.html are broken. This is fixed in 0.5.0, but mdbook-cmdrun needs to address the breaking changes
[output.html.fold]
enable = true
level = 0

[output.html.redirect]
"/adding_board_support.html" = "adding-board-support.html"
"/async_support.html" = "async-support.html"
"/build_system.html" = "build-system.html"
"/debug_console.html" = "debug-console.html"
"/getting_started.html" = "getting-started.html"
"/hardware_functionality_support.html" = "hardware-functionality-support.html"

[preprocessor.cmdrun]
