[book]
authors = [
  "Kaspar Schleiser",
  "Emmanuel Baccelli",
  "Christian Ams√ºss",
  "Elena Frank",
]
language = "en"
multilingual = false
src = "src"
title = "Ariel OS manual"

[output.html]
git-repository-url = "https://github.com/ariel-os/ariel-os"
edit-url-template = "https://github.com/ariel-os/ariel-os/edit/main/book/{path}"

[output.html.redirect]
"/build_system.html" = "build-system.html"
"/getting_started.html" = "getting-started.html"

[preprocessor.cmdrun]
