name: Preview PR docs

# commenting needs these
permissions:
  pull-requests: write

on:
  workflow_run:
    workflows: ["Deploy docs"]
    types:
      - completed

jobs:
  preview:
    runs-on: ubuntu-latest
    if: >
      ${{ github.event.workflow_run.event == 'pull_request' &&
      github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: "Get PR number"
        uses: actions/download-artifact@634f93cb2916e3fdff6788551b99b062d0335ce0 # v5
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          run-id: ${{ github.event.workflow_run.id }}
          name: pr-number

      - name: "Store PR number in output"
        id: "pr"
        run: echo "pr=$(cat pr)" >> $GITHUB_OUTPUT

      - uses: actions/download-artifact@634f93cb2916e3fdff6788551b99b062d0335ce0 # v5
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          run-id: ${{ github.event.workflow_run.id }}
          name: pr-${{ steps.pr.outputs.pr }}-docs
          path: ./_site

      - name: Install surge
        run: npm --global install surge

      - name: Deploy PR preview
        run: |
          surge ./_site ${{ github.repository_owner }}-docs-preview-pr${{ steps.pr.outputs.pr }}.surge.sh --token ${{ secrets.SURGE_TOKEN }}

      - name: Comment URL
        uses: marocchino/sticky-pull-request-comment@773744901bac0e8cbb5a0dc842800d45e9b2b405 # v2
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          number: ${{ steps.pr.outputs.pr }}
          message: |
            ðŸš€ Documentation preview deployed to <https://${{ github.repository_owner }}-docs-preview-pr${{ steps.pr.outputs.pr }}.surge.sh/dev/docs/api/ariel_os/>
            ðŸ“” Book preview deployed to <https://${{ github.repository_owner }}-docs-preview-pr${{ steps.pr.outputs.pr }}.surge.sh/dev/docs/book/>
