name: Dependency Vetting
on:
  pull_request:
    branches:
      - main
  merge_group:

jobs:
  cargo-vet:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6

      - id: get_toolchain
        run: echo "toolchain=$(scripts/rust-toolchain.sh)" >> $GITHUB_OUTPUT

      - name: Install toolchain
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ steps.get_toolchain.outputs.toolchain }}

      - name: Install cargo-vet
        uses: taiki-e/install-action@0e76c5c569f13f7eb21e8e5b26fe710062b57b62 # v2
        with:
          tool: cargo-vet@0.10.0

      - name: Invoke cargo-vet
        run: cargo vet --locked
