name: Dependency Vetting
on:
  pull_request:
    branches:
      - main
  merge_group:

jobs:
  cargo-vet:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6

      - id: get_toolchain
        run: echo "toolchain=$(scripts/rust-toolchain.sh)" >> $GITHUB_OUTPUT

      - name: Install toolchain
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ steps.get_toolchain.outputs.toolchain }}

      - name: Install cargo-vet
        uses: taiki-e/install-action@870266878ed54ea9ceb25502c53e42aa939585a6 # v2
        with:
          tool: cargo-vet@0.10.2

      - name: Invoke cargo-vet
        run: cargo vet --locked
