[package]
name = "ariel-os-random"
version = "0.2.0"
edition.workspace = true
rust-version.workspace = true
repository.workspace = true
license.workspace = true

[dependencies]
rand-core-06 = { package = "rand_core", version = "0.6" }
rand_core = { workspace = true }

embassy-sync = { workspace = true }

rand_chacha = { version = "0.9.0", default-features = false, optional = true }
rand_pcg = "0.9.0"

getrandom = { version = "0.3.3", optional = true }

[features]
## If set, the one global RNG is also a cryptographically secure pseudo
## random number generator (CSPRNG), and thus, a `CryptoRng` can be produced.
csprng = ["dep:getrandom", "dep:rand_chacha"]

[lints]
workspace = true
