[package]
name = "ariel-os-runqueue"
version = "0.2.0"
edition.workspace = true
rust-version.workspace = true
description = "Ariel OS runqueue implementation"
license.workspace = true

[dependencies]
defmt = { workspace = true, optional = true }

# This is required so that F* can find the required F* model of the Rust core
# lib, as documented in the hax documentation:
# https://hacspec.org/book/quick_start/intro.html#setup-the-crate-you-want-to-verify
[target.'cfg(hax)'.dependencies]
hax-lib = "0.3.6"

[features]
defmt = ["dep:defmt"]

_test = []

[lints]
workspace = true
